#!/bin/bash

set -ex

for project in "figwheel-main"; do
  pushd ${project}
  make testit
  popd
done

# TODO: add "figwheel-core"
for project in "figwheel-repl" "plugin" "sidecar" "support"; do
  pushd ${project}
  lein test
  popd
done
